server:
  http:
    addr: 0.0.0.0:8001
    timeout: 100s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 100s
data:
  database:
    driver: mysql
    source: root:8888.216@tcp(127.0.0.1:3306)/lehu_data_collect_data?parseTime=True&loc=Local
  redis:
    addr: 127.0.0.1:6379
    read_timeout: 0.2s
    write_timeout: 0.2s
